[build-system]
requires = ["hatchling","hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "skinsense"
version = "0.0.1"
authors = [
  { name="Himantveer Kaur" },
  { name="Muskan Kohli" },
  { name="Ansh Bindal" },
  { name="Arnav Chandla" },
]
description = "SkinSense -- AI skin analysis and skincare recommendation app (UCS503P project)"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    # See: https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: POSIX",
    "Programming Language :: Unix Shell",
]
dependencies = ["click"]

[project.urls]
Homepage = "https://github.com/Himmat913/UCS503P-202627-SkinSense"
Issues = "https://github.com/Himmat913/UCS503P-202627-SkinSense/issues"

# Adapted from https://stackoverflow.com/a/50156706
[tool.pytest.ini_options]
pythonpath = [
  "code/backend"
]
# THE END -------------------------------------------